lb:
  image: tutum/haproxy
  ports:
    - "80:80"
  links: 
    - web
web:
  image: gochiba/php_lamp
  expose:
    - "80"
  volumes:
    - ./html:/var/www/html
  links:
    - db
db:
  image: mysql
  volumes:
    - /mnt/sda1/var/lib/mysql:/var/lib/mysql:rw
    - ./my.cnf.server:/etc/mysql/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=MySQLAdmin
